#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored


# FONT="JetBrainsMono Nerd Font"
FONT="Hack Nerd Font"
PADDINGS=3

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
POPUP_BACKGROUND_COLOR=$BLACK
POPUP_BORDER_COLOR=$COMMENT

CORNER_RADIUS=15
BORDER_WIDTH=2

SHADOW=on
# FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
FONT="Hack Nerd Font"
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components
POPUP_CLICK_SCRIPT="sketchybar -m --set \"\$NAME\" popup.drawing=toggle" # The script that toggles the popup windows

PADDINGS=3 # All paddings use this value (icon, label, background and bar paddings)
SEGMENT_SPACING=13 # The spacing between segments

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=3

SHADOW=on
SHADOW_DISTANCE=3
SHADOW_ANGLE=35

# Setting up the general bar appearance and default values
sketchybar --bar     height=30                                           \
                     blur_radius=20                                       \
                     color=$BAR_COLOR                                    \
                     corner_radius=15                                     \
                     font_smoothing=off                                  \
                     margin=5                                        \
                     padding_left=4                                      \
                     padding_right=0                                     \
                     position=top                                        \
                     shadow=on                                          \
                     sticky=on \
                     topmost=off                                         \
                     y_offset=5                                        \
                     notch_width=0                                       \
                                                                         \
	--default updates=when_shown \
            icon.font="$FONT:Bold:13.5" \
            icon.color="$ICON_COLOR" \
            icon.padding_left="$PADDINGS" \
            icon.padding_right="$PADDINGS" \
            label.font="$FONT:Bold:13.0" \
            label.color="$LABEL_COLOR" \
            label.padding_left="$PADDINGS" \
            label.padding_right="$PADDINGS" \
            background.padding_right="$PADDINGS" \
            background.padding_left="$PADDINGS" \
            popup.background.border_width=1 \
            popup.background.corner_radius=11 \
            popup.background.border_color="$POPUP_BORDER_COLOR" \
            popup.background.color="$POPUP_BACKGROUND_COLOR" \
            popup.background.shadow.drawing="$SHADOW"
# Template for the segment labels, i.e. space name, active app, date, ...
sketchybar --add item           label_template left                          \
           --set label_template icon.drawing=off                             \
                                label.font="$FONT:Black:12.0"                \
                                label.padding_right=5                        \
                                click_script="$PLUGIN_DIR/toggle_bracket.sh" \
                                background.padding_left=$SEGMENT_SPACING     \
                                background.padding_right=0                   \
                                drawing=off

source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/github.sh"
# source "$ITEM_DIR/network.sh"
# source "$ITEM_DIR/memory.sh"

 source "$ITEM_DIR/spotify.sh"
 # source "$ITEM_DIR/system.sh"
 source "$ITEM_DIR/yabai_window.sh"
 source "$ITEM_DIR/front_app.sh"

# source "$ITEM_DIR/calendar.sh"
# source "$ITEM_DIR/cpu.sh" |
# source "$ITEM_DIR/system.sh"

source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/caffeinate.sh"

############## FINALIZING THE SETUP ##############
sketchybar --hotload true
sketchybar --update

############## Animation ########################
sketchybar --animate sin 30 --bar y_offset=0 notch_width=200 margin=0 shadow=on

echo "sketchybar configuation loaded.."

