general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/themes/catppuccin-latte.toml"
  # "~/.config/alacritty/themes/catppuccin-frappe.toml"
   "~/.config/alacritty/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"


[font]
size = 13

[font.normal]
#family = "Hack Nerd Font Mono"
family = "Iosevka"
#style = "Fixed Slab"

[window]
decorations = "none"

[window.padding]
x = 7
y = 0

[selection]
save_to_clipboard = true
